services:
  - type: web
    name: plottwist-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_TMDB_API_KEY
        value:  ${VITE_TMDB_API_KEY}
      - key: VITE_YOUTUBE_API_KEY
        value:  ${VITE_YOUTUBE_API_KEY}